# Zizmor configuration
# Suppress cache-poisoning warnings for actions/setup-node@v4
# These are false positives - no packageManager field in package.json means no auto-caching
# Workflows have read-only permissions, minimizing actual risk

rules:
  cache-poisoning:
    ignore:
      - ci.yml:29
      - ci.yml:63
