name: Continuous Integration
permissions: read-all

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  dist-management:
    uses: ./.github/workflows/dist-management.yml

  test-javascript:
    name: JavaScript Tests
    runs-on: ubuntu-latest
    needs: [dist-management]

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test
