name: Continuous Integration
permissions: read-all

on:
  workflow_run:
    workflows: ["Dist Management"]
    types: [completed]
    branches: [main]
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - 'releases/*'
    paths-ignore:
      - '**.md'

jobs:
  test-javascript:
    name: JavaScript Tests
    runs-on: ubuntu-latest
    # Only run if dist management succeeded or if this is a direct trigger
    if: github.event.workflow_run.conclusion == 'success' || github.event_name != 'workflow_run'

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test
